import Popup from "./classes/Popup.js";
import Api from "./classes/Api.js";
import Layout from "./classes/Layout.js";
import Blog from "./classes/Blog.js";
import Cases from "./classes/Cases.js";
import User from "./classes/User.js";
import Patients from "./classes/Patients.js";
import Treatments from "./classes/Treatments.js";
import Budgets from "./classes/Budgets.js";
import Invoices from "./classes/Invoices.js";
import Consents from "./classes/Consents.js";
import Doctors from "./classes/Doctors.js";

export const popup = new Popup();
export const api = new Api();
export const layout = new Layout();
export const blog = new Blog();
export const user = new User();
export const cases = new Cases();
export const patients = new Patients();
export const treatments = new Treatments();
export const budgets = new Budgets();
export const invoices = new Invoices();
export const consents = new Consents();
export const doctors = new Doctors();