<section class="section page-header">
    <div class="container">
        <h1>Implantes dentales</h1>
        <p>Lorem ipsum dolor sit amet, consect adipiscing elit. Nunc volutpat pellentesque leo.</p>
    </div>
</section>

<section class="section treatment">
    <div class="container">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sit amet elementum orci. Nulla tristique magna nibh, at tincidunt nunc lacinia in. Duis tincidunt tellus et ipsum ultricies, quis auctor ex dapibus. Mauris eu metus suscipit, ullamcorper mi eu, porta odio. Ut volutpat, nibh non sagittis fringilla, lectus sapien tempor nisl, quis laoreet justo tellus posuere felis. In ornare diam et nibh congue tempor. Mauris ullamcorper tincidunt condimentum. Nulla vitae tristique ante. Sed vitae leo in nunc congue porta. Integer a lorem id sapien sollicitudin mollis pretium vitae enim.</p>
        <img src="/build/img/blog/blog5.jpg" alt="Imagen 1" class="image-right">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque mattis turpis id augue suscipit, in gravida augue laoreet. Aliquam tincidunt, turpis quis consequat posuere, odio erat sagittis arcu, in tempor purus diam eget nisl. Curabitur sit amet eros nec nisi pharetra vulputate. Sed fringilla purus eu leo rhoncus, ut ornare ex aliquam. Donec ut bibendum est. Nam mauris felis, pharetra at feugiat non, consequat vitae ligula. Quisque nisl diam, euismod vel sem pulvinar, venenatis congue magna. Nam maximus massa sit amet varius ultrices. Nulla sed feugiat felis. Vestibulum tempor porta arcu, sed accumsan quam condimentum at. Suspendisse vel porta odio, in mattis ante. Aliquam rutrum lacus non nulla placerat, vel tristique dui facilisis. Sed mattis feugiat sodales. Nullam feugiat euismod venenatis. Curabitur tincidunt viverra velit, ac porta erat posuere at.</p>
        <p>Ut ac ultrices augue. Donec in arcu ac neque feugiat tempus. Curabitur magna urna, scelerisque id purus eget, mollis varius lacus. Donec congue, tellus sit amet posuere mattis, lacus magna scelerisque elit, quis gravida lectus leo at sem. Sed bibendum quam sit amet tempor consequat. In id luctus lacus. In vehicula sollicitudin justo non dictum. Praesent sed justo vel nisl porttitor accumsan non non elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in tortor id urna molestie feugiat. Donec fermentum dolor a bibendum egestas. Cras nec scelerisque nisl.</p>
        <img src="/build/img/blog/blog4.jpg" alt="Imagen 2" class="image-left">
        <p>Sed felis velit, volutpat nec ultricies eget, consequat id justo. Maecenas hendrerit, nulla a vulputate sagittis, dui mauris porttitor tortor, non sollicitudin neque augue ut odio. Integer nibh elit, convallis eu facilisis vel, accumsan et ex. Quisque a elit non lorem elementum placerat at sed nulla. In molestie vehicula finibus. Praesent maximus tortor vitae ante imperdiet, elementum maximus turpis tempor. Suspendisse posuere sem sed risus euismod posuere. Nullam vel enim at eros egestas pulvinar sed venenatis massa. Donec vel euismod tellus, in ultrices sapien. Proin euismod sed turpis in luctus.</p>
        <p>Etiam ac augue metus. Maecenas cursus tortor sed ipsum maximus, sit amet ultrices sem luctus. Integer interdum libero quis elit aliquam, et egestas arcu facilisis. Sed quis ex in enim fermentum congue. Proin congue ornare malesuada. Donec rutrum molestie fermentum. Ut risus dui, malesuada nec quam vel, ultricies commodo magna. Integer justo leo, interdum sit amet tincidunt nec, venenatis et justo. Nam nibh elit, congue vel ex vitae, consequat lacinia libero. Sed erat odio, congue et mattis ac, finibus et urna.</p>
    </div>
</section>